// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parcial.Data;
using parcial.Models;

#nullable disable

namespace practica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230923022444_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity<Parcial>(b =>
            {
                b.Property<int>("DNI")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Nombre")
                    .HasColumnType("TEXT");

                b.Property<string>("Apellidos")
                    .HasColumnType("TEXT");

                b.HasKey("DNI");

                b.ToTable("Parcial");
            });
#pragma warning restore 612, 618
        }
    }
}

